### ISSUE TITLE
Error: Type variables can't be used as constants

### ISSUE THREAD

**Issue by mbegench** [Tienisto/riverpie#1]
lib/src/notifier/base_notifier.dart:764:15: Error: Type variables can't be used as
constants.
[        ]           (T, R) stateWithResult => stateWithResult,

**Comment by Tienisto** [comment]
Can you explain how this error happened?

**Comment by Tienisto** [comment]
I think you had a compile time error because your Dart version is outdated.

Feel free to comment if you have concrete reproduction steps.

**Comment by mbegench** [comment]
My Flutter Version is: 3.10.2, Im solved this problem by changing version of plugin
