### ISSUE TITLE
Custom Data type failing on ReduxNotifier.dispatchAsync

### ISSUE THREAD

**Issue by ekottifiok** [Tienisto/riverpie#4]
If I use a custom data type in my Chat model like the ChatStatus

![error_3](https://github.com/refena/refena/assets/81968053/983e586a-9d2f-4549-a90a-c649f88cc8c3)

And run my application  when this part of the application runs 

![error_2](https://github.com/refena/refena/assets/81968053/455d9c10-4d9a-4272-924f-366a70106da9)

```
_ChainedMapperException (MapperException: Failed to encode (FavoriteDevice).chats(List<Chat>).item(Chat).status[ChatStatus.delivered]: Unknown type ChatStatus. Did you forgot to annotate the class or register a custom mapper?)
```

![error_1](https://github.com/refena/refena/assets/81968053/a8dcd840-6cc8-4cd8-9169-9dcc81a063d6)

Can someone help me fix this error please

**Comment by Tienisto** [comment]
This is a dart_mappable issue and should be unrelated to refena.

I think you need to add `@MappableEnum` to the enum.

**Comment by ekottifiok** [comment]
Thanks a lot for replying, I'm really grateful

I fails on any custom data type
I tried using AssetsGenImage from the FlutterGen library as a datatype in a class and it failed throwing the exact same error
I don't mean to say refena is defective but I can't seem to fix this error for days

Edit: It does work without errors thanks a lot, really appreciate.

Please I need a favor, I teaching myself Flutter and I need some help like if I have an error I can't seem to fix.
How could I reach you instead of opening an issue?

**Comment by ekottifiok** [comment]
It really was a dart_mappable issue and should was unrelated to refena.

Adding @MappableEnum to the enum fixed the issue.
